### PR TITLE
Feature/rework

### PR DESCRIPTION
**Pull request by pointnet**
This was not working as expected for me so I tried to rework the plugin based on generate-package philosophy.

I still have 2 tests not passing but I don't understand why at this point, my knowledge of the ecosystem still have to grow ;-)

```
generate-contributing generator (CLI) should run the default task using the `generate-contributing` name
generate-contributing generator (CLI) should run the contributing task explicitly using the `contributing` generator alias
```

### CODE REVIEW

**Comment by jonschlinkert** [comment]
looks great! I think this was one of the first generators, I like your updates, it's much better!

would you mind rebasing, and updating the pr so I can merge cleanly?

**Comment by pointnet** [comment]
It's my first `rebase` so I hope this is what you were looking for ^^

**Comment by jonschlinkert** [comment]
thanks! looks good. 

fwiw I fixed the bug that was preventing the `ask` helper from working with `homepage`. When a question isn't registered, it should just use the property name in the prompt.

**Comment by jonschlinkert** [comment]
Ok, I further simplified the generator based on some recent changes. I added support for `-d` to generate, so both `--dest` and `-d` will set `app.cwd`. 

Also I initially did `var dest = app.options.dest || app.cwd` when all of the CLI logic wasn't implemented yet, but `app.options.dest` will [update app.cwd](https://github.com/generate/generate/blob/master/lib/mixins.js#L132-L133), so we should be able to just do `app.cwd` instead.

Last, I removed `common-questionst` since  `generate-defaults` should provide everything this generator needs (based on bug fixes that were made yesterday). 

If it's not too much trouble, let me know if this works for you. Note that you will need to reinstall `generate` globally again (sorry, the changes will slow down very soon!)

**Comment by pointnet** [comment]
perfect!

**Pull request merged**
